enum EnglishStrings {
    static let values: [L10nKey: String] = [
        .add: "Add",
        .addRepository: "Add Restic Repository",
        .allProtected: "All protected",
        .appIcon: "App Icon",
        .appIconDefault: "Default",
        .appIconDimensional: "Dimensional",
        .appIconGlass: "Glass",
        .appIconNeon: "Neon",
        .appIconOrbitCheck: "Orbit Check",
        .appIconVaultSeal: "Vault Seal",
        .appIconSnapshotLayers: "Snapshots",
        .appIconTimeCapsule: "Time Capsule",
        .appIconIntegrityPrism: "Prism",
        .appIconSignalArchive: "Signal",
        .appIconMinimalRibbon: "Ribbon",
        .appIconChecksumWave: "Checksum",
        .backupHealthUnknown: "Backup health unknown",
        .backupNeedsAttention: "Backup needs attention",
        .cancel: "Cancel",
        .cli: "CLI",
        .cliPath: "CLI path",
        .chooseFolder: "Choose...",
        .confidence: "Confidence",
        .containers: "Containers",
        .copy: "Copy",
        .copyCommand: "Copy command",
        .copyRestoreCommand: "Copy Restore Command",
        .copied: "Copied",
        .criticalIssues: "Critical Issues",
        .dashboard: "Dashboard",
        .docker: "Docker",
        .dockerMissing: "Missing",
        .dockerNotRunning: "Not running",
        .dockerRunning: "Running",
        .dockerStartDetail: "Restorix can only inspect containers and volumes while the Docker daemon is running.",
        .dockerStartTitle: "Start Docker or OrbStack",
        .enabled: "Enabled",
        .disabled: "Disabled",
        .enable: "Enable",
        .disable: "Disable",
        .error: "Error",
        .exportReport: "Export Report",
        .generate: "Generate",
        .generateReport: "Generate Report",
        .healthAllProtected: "Health: All protected",
        .healthAtRisk: "Health: At risk",
        .healthNeedsReview: "Health: Needs review",
        .healthUnknown: "Health: Unknown",
        .installResticDetail: "Restorix uses restic snapshots to verify whether Docker volumes are backed up.",
        .installResticTitle: "Install restic",
        .language: "Language",
        .lastBackup: "Last Backup",
        .lastScan: "Last scan",
        .launchAtLogin: "Open at login",
        .localNotifications: "Local notifications",
        .looseMatching: "Loose matching",
        .markdownReport: "Markdown Report",
        .name: "Name",
        .noReportGenerated: "No report generated",
        .noReportGeneratedMessage: "Generate a Markdown report from the latest scan result.",
        .noRepositoriesConfigured: "No repositories configured",
        .noRepositoriesConfiguredMessage: "Add a restic repository so Restorix can compare snapshots with Docker volumes.",
        .noRiskyVolumes: "No risky volumes found in the latest scan.",
        .noScanResults: "No scan results yet",
        .noScanResultsMessage: "Run your first scan to check whether your Docker volumes are protected.",
        .noVolumesFound: "No volumes found",
        .noVolumesFoundMessage: "Run a scan after Docker is running to inspect Docker volume health.",
        .none: "None",
        .notSet: "Not set",
        .notScanned: "Not scanned",
        .nextSteps: "Next Steps",
        .openDashboard: "Open Dashboard",
        .openVolumes: "Open Volumes",
        .productSubtitle: "Restorix checks whether Docker volumes are actually restorable.",
        .passwordEnv: "Password env",
        .password: "Repository password (stored in Keychain)",
        .protected: "Protected",
        .reason: "Reason",
        .repositories: "Repositories",
        .repositoryLocation: "Repository Location",
        .reportGenerateMessage: "Generate a Markdown report from the latest scan result.",
        .reports: "Reports",
        .restic: "Restic",
        .resticAvailable: "Available",
        .resticMissing: "Missing",
        .resticRepoAddDetail: "Without a repository, Restorix can list volumes but cannot prove that any backup exists.",
        .resticRepoAddTitle: "Add a restic repository",
        .restoreCommand: "Restore command",
        .safeRestoreCommand: "Safe restore command",
        .snapshotHostname: "Snapshot hostname",
        .save: "Save",
        .saveSettings: "Save Settings",
        .scan: "Scan",
        .scanNow: "Scan Now",
        .scanSettings: "Scan",
        .scanning: "Scanning",
        .settings: "Settings",
        .staleThreshold: "Stale threshold",
        .statusNotScanned: "Status: Not scanned",
        .statusLine: "Status",
        .status: "Status",
        .systemDefault: "System default",
        .unknownReviewDetail: "Unknown means Restorix could not find enough reliable snapshot evidence yet.",
        .unknownReviewTitle: "Review unknown volumes",
        .unknown: "Unknown",
        .unprotected: "Unprotected",
        .volume: "Volume",
        .volumeHealth: "Volume Health",
        .volumes: "Volumes",
        .volumesAtRisk: "Volumes at risk",
        .warnings: "Warnings",
        .stale: "Stale",
        .hours: "hours",
        .cliHint: "Leave empty to use the bundled restorix binary or Homebrew fallback.",
        .configureCLI: "Configure CLI",
        .envNameOnly: "Restorix stores the environment variable name, not your password.",
        .openDocker: "Open Docker",
        .quit: "Quit",
        .never: "Never",
        .repository: "Repository",
        .remove: "Remove",
        .removeRepository: "Remove Repository",
        .repositoryReady: "Repository is reachable",
        .repositoryTestFailed: "Repository test failed",
        .showDockIcon: "Show Dock icon",
        .snapshots: "snapshots",
        .testRepository: "Test Repository",
        .testing: "Testing",
        .reviewVolumes: "Review Volumes"
    ]
}

