enum SimplifiedChineseStrings {
    static let values: [L10nKey: String] = [
        .add: "添加",
        .addRepository: "添加 Restic 仓库",
        .allProtected: "全部已保护",
        .appIcon: "应用图标",
        .appIconDefault: "默认",
        .appIconDimensional: "立体",
        .appIconGlass: "玻璃",
        .appIconNeon: "霓虹",
        .appIconOrbitCheck: "轨道校验",
        .appIconVaultSeal: "保险库印章",
        .appIconSnapshotLayers: "快照",
        .appIconTimeCapsule: "时间胶囊",
        .appIconIntegrityPrism: "棱镜",
        .appIconSignalArchive: "信号档案",
        .appIconMinimalRibbon: "缎带",
        .appIconChecksumWave: "校验",
        .backupHealthUnknown: "备份健康状态未知",
        .backupNeedsAttention: "备份需要关注",
        .cancel: "取消",
        .cli: "CLI",
        .cliPath: "CLI 路径",
        .chooseFolder: "选择...",
        .confidence: "匹配置信度",
        .containers: "容器",
        .copy: "复制",
        .copyCommand: "复制命令",
        .copyRestoreCommand: "复制恢复命令",
        .copied: "已复制",
        .criticalIssues: "关键问题",
        .dashboard: "仪表盘",
        .docker: "Docker",
        .dockerMissing: "未安装",
        .dockerNotRunning: "未运行",
        .dockerRunning: "运行中",
        .dockerStartDetail: "只有 Docker daemon 正在运行时，Restorix 才能检查容器和 volume。",
        .dockerStartTitle: "启动 Docker 或 OrbStack",
        .enabled: "已启用",
        .disabled: "已停用",
        .enable: "启用",
        .disable: "停用",
        .error: "错误",
        .exportReport: "导出报告",
        .generate: "生成",
        .generateReport: "生成报告",
        .healthAllProtected: "健康：全部已保护",
        .healthAtRisk: "健康：有风险",
        .healthNeedsReview: "健康：需要检查",
        .healthUnknown: "健康：未知",
        .installResticDetail: "Restorix 使用 restic snapshots 来确认 Docker volumes 是否真的被备份。",
        .installResticTitle: "安装 restic",
        .language: "语言",
        .lastBackup: "最近备份",
        .lastScan: "最近扫描",
        .launchAtLogin: "登录时打开",
        .localNotifications: "本地通知",
        .looseMatching: "宽松匹配",
        .markdownReport: "Markdown 报告",
        .name: "名称",
        .noReportGenerated: "还没有生成报告",
        .noReportGeneratedMessage: "基于最近一次扫描生成 Markdown 健康报告。",
        .noRepositoriesConfigured: "还没有配置仓库",
        .noRepositoriesConfiguredMessage: "添加一个 restic 仓库后，Restorix 才能把 snapshots 和 Docker volumes 进行比对。",
        .noRiskyVolumes: "最近一次扫描没有发现高风险 volume。",
        .noScanResults: "还没有扫描结果",
        .noScanResultsMessage: "运行第一次扫描，检查 Docker volumes 是否被保护。",
        .noVolumesFound: "没有发现 volumes",
        .noVolumesFoundMessage: "Docker 运行后再扫描，Restorix 会检查 Docker volume 健康状态。",
        .none: "无",
        .notSet: "未设置",
        .notScanned: "未扫描",
        .nextSteps: "下一步",
        .openDashboard: "打开仪表盘",
        .openVolumes: "打开 Volumes",
        .productSubtitle: "Restorix 会检查 Docker volumes 是否真的可恢复。",
        .passwordEnv: "密码环境变量",
        .password: "仓库密码（存储在钥匙串）",
        .protected: "已保护",
        .reason: "原因",
        .repositories: "仓库",
        .repositoryLocation: "仓库位置",
        .reportGenerateMessage: "基于最近一次扫描生成 Markdown 健康报告。",
        .reports: "报告",
        .restic: "Restic",
        .resticAvailable: "可用",
        .resticMissing: "未安装",
        .resticRepoAddDetail: "没有仓库时，Restorix 可以列出 volumes，但无法证明备份存在。",
        .resticRepoAddTitle: "添加 restic 仓库",
        .restoreCommand: "恢复命令",
        .safeRestoreCommand: "安全恢复命令",
        .snapshotHostname: "快照主机名",
        .save: "保存",
        .saveSettings: "保存设置",
        .scan: "扫描",
        .scanNow: "立即扫描",
        .scanSettings: "扫描",
        .scanning: "扫描中",
        .settings: "设置",
        .staleThreshold: "过期阈值",
        .statusNotScanned: "状态：未扫描",
        .statusLine: "状态",
        .status: "状态",
        .systemDefault: "跟随系统",
        .unknownReviewDetail: "Unknown 表示 Restorix 还没有找到足够可靠的 snapshot 证据。",
        .unknownReviewTitle: "检查未知 volumes",
        .unknown: "未知",
        .unprotected: "未保护",
        .volume: "Volume",
        .volumeHealth: "Volume 健康",
        .volumes: "Volumes",
        .volumesAtRisk: "Volumes 有风险",
        .warnings: "警告",
        .stale: "已过期",
        .hours: "小时",
        .cliHint: "留空时使用 App 内置的 restorix，或 Homebrew 路径中的 restorix。",
        .configureCLI: "配置 CLI",
        .envNameOnly: "Restorix 只保存环境变量名称，不保存你的密码。",
        .openDocker: "打开 Docker",
        .quit: "退出",
        .never: "从未",
        .repository: "仓库",
        .remove: "删除",
        .removeRepository: "删除仓库",
        .repositoryReady: "仓库可访问",
        .repositoryTestFailed: "仓库测试失败",
        .showDockIcon: "显示 Dock 图标",
        .snapshots: "个 snapshots",
        .testRepository: "测试仓库",
        .testing: "测试中",
        .reviewVolumes: "检查 Volumes"
    ]
}
